CREATE TABLE NUEVOABARCA.B_PLACE
(
    B_PLACE_ID   NUMBER,
    B_PLACE      NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NUEVOABARCA.FIELD
(
    FIELD_ID   NUMBER,
    FIELD      NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NUEVOABARCA.CATEGORY
(
    CATEGORY_ID   NUMBER,
    CATEGORY      NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NUEVOABARCA.COUNTRY
(
    COUNTRY_ID   NUMBER,
    COUNTRY      NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NUEVOABARCA.PRIZE_FIELD
(
    PRIZE_ID   NUMBER,
    FIELD_ID    NUMBER
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NUEVOABARCA.WINNER_PRIZE
(
    WINNER_PRIZE_ID   NUMBER,
    WINNER_ID           NUMBER,
    PRIZE_ID         NUMBER
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NUEVOABARCA.PRIZE
(
    PRIZE_ID      NUMBER,
    YEAR           DATE,
    MOTIVACION     NVARCHAR2 (250),
    CATEGORY_ID   NUMBER,
    COUNTRY_ID     NUMBER,
    NOMBRE         NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NUEVOABARCA.RESIDENCE
(
    RESIDENCE_ID   NUMBER,
    RESIDENCE      NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NUEVOABARCA.RESIDENCE_PRIZE
(
    PRIZE_ID       NUMBER,
    RESIDENCE_ID   NUMBER
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NUEVOABARCA.ROLES
(
    ROLES_ID   NUMBER,
    ROLES      NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NUEVOABARCA.WINNER
(
    WINNER_ID         NUMBER,
    NOMBRE          NVARCHAR2 (250),
    BIRTHDAY        DATE,
    B_PLACE_ID   NUMBER,
    ROLES_ID          NUMBER
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE UNIQUE INDEX NUEVOABARCA.B_PLACE_PK
    ON NUEVOABARCA.B_PLACE (B_PLACE_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NUEVOABARCA.FIELD_PK
    ON NUEVOABARCA.FIELD (FIELD_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NUEVOABARCA.CATEGORY_PK
    ON NUEVOABARCA.CATEGORY (CATEGORY_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NUEVOABARCA.COUNTRY_PK
    ON NUEVOABARCA.COUNTRY (COUNTRY_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NUEVOABARCA.WINNER_PRIZE_PK
    ON NUEVOABARCA.WINNER_PRIZE (WINNER_PRIZE_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NUEVOABARCA.PRIZE_PK
    ON NUEVOABARCA.PRIZE (PRIZE_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NUEVOABARCA.RESIDENCE_PK
    ON NUEVOABARCA.RESIDENCE (RESIDENCE_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NUEVOABARCA.ROLES_PK
    ON NUEVOABARCA.ROLES (ROLES_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NUEVOABARCA.WINNER_PK
    ON NUEVOABARCA.WINNER (WINNER_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

ALTER TABLE NUEVOABARCA.B_PLACE ADD (
  CONSTRAINT B_PLACE_PK
  PRIMARY KEY
  (B_PLACE_ID)
  USING INDEX NUEVOABARCA.B_PLACE_PK
  ENABLE VALIDATE);

ALTER TABLE NUEVOABARCA.FIELD ADD (
  CONSTRAINT FIELD_PK
  PRIMARY KEY
  (FIELD_ID)
  USING INDEX NUEVOABARCA.FIELD_PK
  ENABLE VALIDATE);

ALTER TABLE NUEVOABARCA.CATEGORY ADD (
  CONSTRAINT CATEGORY_PK
  PRIMARY KEY
  (CATEGORY_ID)
  USING INDEX NUEVOABARCA.CATEGORY_PK
  ENABLE VALIDATE);

ALTER TABLE NUEVOABARCA.COUNTRY ADD (
  CONSTRAINT COUNTRY_PK
  PRIMARY KEY
  (COUNTRY_ID)
  USING INDEX NUEVOABARCA.COUNTRY_PK
  ENABLE VALIDATE);

ALTER TABLE NUEVOABARCA.WINNER_PRIZE ADD (
  CONSTRAINT WINNER_PRIZE_PK
  PRIMARY KEY
  (WINNER_PRIZE_ID)
  USING INDEX NUEVOABARCA.WINNER_PRIZE_PK
  ENABLE VALIDATE);

ALTER TABLE NUEVOABARCA.PRIZE ADD (
  CONSTRAINT PRIZE_PK
  PRIMARY KEY
  (PRIZE_ID)
  USING INDEX NUEVOABARCA.PRIZE_PK
  ENABLE VALIDATE);

ALTER TABLE NUEVOABARCA.RESIDENCE ADD (
  CONSTRAINT RESIDENCE_PK
  PRIMARY KEY
  (RESIDENCE_ID)
  USING INDEX NUEVOABARCA.RESIDENCE_PK
  ENABLE VALIDATE);

ALTER TABLE NUEVOABARCA.ROLES ADD (
  CONSTRAINT ROLES_PK
  PRIMARY KEY
  (ROLES_ID)
  USING INDEX NUEVOABARCA.ROLES_PK
  ENABLE VALIDATE);

ALTER TABLE NUEVOABARCA.WINNER ADD (
  CONSTRAINT WINNER_PK
  PRIMARY KEY
  (WINNER_ID)
  USING INDEX NUEVOABARCA.WINNER_PK
  ENABLE VALIDATE);

--constraints

ALTER TABLE nuevoabarca.prize
    ADD CONSTRAINT FK_prize02 FOREIGN KEY (category_id)
        REFERENCES nuevoabarca.category (category_id)
        ENABLE VALIDATE;

ALTER TABLE nuevoabarca.winner_prize
    ADD CONSTRAINT FK_prize03 FOREIGN KEY (prize_id)
        REFERENCES NUEVOABARCA.prize (prize_id)
        ENABLE VALIDATE;

ALTER TABLE NUEVOABARCA.RESIDENCE_PRIZE
    ADD CONSTRAINT FK_prize04 FOREIGN KEY (prize_id)
        REFERENCES NUEVOABARCA.prize (prize_id)
        ENABLE VALIDATE;

ALTER TABLE NUEVOABARCA.prize_field
    ADD CONSTRAINT FK_prize05 FOREIGN KEY (prize_id)
        REFERENCES NUEVOABARCA.prize (prize_id)
        ENABLE VALIDATE;

ALTER TABLE NUEVOABARCA.prize_field
    ADD CONSTRAINT FK_field01 FOREIGN KEY (field_id)
        REFERENCES NUEVOABARCA.field (field_id)
        ENABLE VALIDATE;

ALTER TABLE NUEVOABARCA.winner_prize
    ADD CONSTRAINT FK_winners01 FOREIGN KEY (winner_id)
        REFERENCES NUEVOABARCA.winner (winner_id)
        ENABLE VALIDATE;

ALTER TABLE NUEVOABARCA.winner
    ADD CONSTRAINT FK_winners02 FOREIGN KEY (b_place_id)
        REFERENCES NUEVOABARCA.B_PLACE (b_place_id)
        ENABLE VALIDATE;


ALTER TABLE NUEVOABARCA.residence_prize
    ADD CONSTRAINT FK_res01 FOREIGN KEY (residence_id)
        REFERENCES NUEVOABARCA.residence (residence_id)
        ENABLE VALIDATE;

ALTER TABLE NUEVOABARCA.roles
    ADD CONSTRAINT FK_winners04 FOREIGN KEY (roles_id)
        REFERENCES NUEVOABARCA.winner (roles_id)
        ENABLE VALIDATE;

ALTER TABLE nuevoabarca.prize
    ADD CONSTRAINT FK_prize01 FOREIGN KEY (country_id)
        REFERENCES nuevoabarca.country (country_id)
        ENABLE VALIDATE;

ALTER TABLE NUEVOABARCA.winner
    ADD CONSTRAINT FK_winners04 FOREIGN KEY (roles_id)
        REFERENCES NUEVOABARCA.roles (roles_id)
        ENABLE VALIDATE;

